### ISSUE TITLE
 Incorrect data emied in LogNewVestingSchedule event

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#11]
In the _createVestingSchedule function of the TokenVesting.sol file,
the LogNewVestingSchedule event is emitting incorrect data. Specifically,
the `_vestingCount` parameter is currently set to `currentVestingCount +
1`, but it should be set to `currentVestingCount`.
This discrepancy can lead to confusion and potential issues when tracking
the number of vesting schedules for a beneficiary, and breaks integrations
with other contracts and off-chain systems.

**Comment by GimerStackIt** [comment]
In this case, the use of `currentVestingCount + 1` was correct but confusing. I just simplified the code to make it more readable.
