### ISSUE TITLE
Missing validation of input parameters

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#12]
Some functions from DefispotToken and TokenVesting contracts are lacking any form of validation of their input parameters:

The constructor() of DefispotToken contract lacks validation of initialSpotToMint input parameter, allowing for 0 amount mint of ERC20 token.

The mint() function of DefispotToken contract lacks validation of amount input parameter, allowing for 0 amount mint of ERC20 token. 

The _createVestingSchedule() function of the TokenVesting contract lacks validation of the _beneficiary input parameter against 0x0. 

This lack of validation can lead to token lock if the vesting is non revokable, the cliff period is 0, and the first slice period has passed or after the first cliff period. In these cases, execution of the revoke() function is not possible due to ERC20InvalidReceiver(0x0) error, and the vestingSchedulesTotalAmount variable cannot be reduced (reduction of this variable is required to use the withdraw() function)

**Comment by GimerStackIt** [comment]
Fixed!
