### ISSUE TITLE
Redundant duration check in _createVestingSchedule function

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#14]
In the _computeReleasableAmount function of the TokenVesting.sol
file, the variable vestingSchedule.slicePeriodSeconds is used in a
series of mathematical operations that appear to be redundant.
The current logic calculates vestedSlicePeriods by dividing
timeFromStart by secondsPerSlice, and then multiplies
vestedSlicePeriods by secondsPerSlice to get vestedSeconds. This
essentially cancels out the division and multiplication operations, making
vestedSeconds equivalent to timeFromStart.
This suggests that the slice period is effectively 1 second, which makes the
use of vestingSchedule.slicePeriodSeconds unnecessary in this
context.
Here is the relevant code snippet:
```
/**
* @dev Computes the releasable amount of tokens for a vesting schedule
.
* @return the amount of releasable tokens
*/
function _computeReleasableAmount(
VestingSchedule memory vestingSchedule
) internal view returns (uint256) {
uint256 currentTime = getCurrentTime();
if ((currentTime < vestingSchedule.cliff) || vestingSchedule.revoked)
{
return 0;
} else if (
currentTime >= vestingSchedule.start + vestingSchedule.duration
) {
return vestingSchedule.amountTotal - vestingSchedule.released;
} else {
uint256 timeFromStart = currentTime - vestingSchedule.start;
uint256 secondsPerSlice = vestingSchedule.slicePeriodSeconds;
uint256 vestedSlicePeriods = timeFromStart / secondsPerSlice;
uint256 vestedSeconds = vestedSlicePeriods * secondsPerSlice;
uint256 vestedAmount = (vestingSchedule.amountTotal *
vestedSeconds) / vestingSchedule.duration;
vestedAmount = vestedAmount - vestingSchedule.released;
return vestedAmount;
}
}
```

**Comment by GimerStackIt** [comment]
Fixed! Remove unnecessary variables.
