### ISSUE TITLE
Redundant duration check in `_createVestingSchedule` function

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#15]
In the `_createVestingSchedule` function of the `TokenVesting.sol` file,
there is a redundant check for `_duration > 0`. This check is unnecessary
because the condition `_duration > _cliff` already ensures that
`_duration` is greater than zero, given that `_cliff` is a uint256 and
therefore always greater than or equal to zero.

**Comment by GimerStackIt** [comment]
Fixed!
