### ISSUE TITLE
Unnecessary external call in _createVestingSchedule function

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#16]
In the `_createVestingSchedule` function of the `TokenVesting.sol` file,
there is an unnecessary external call to
`this.computeNextVestingScheduleIdForHolder`. This external call is
gas expensive and could be avoided.
The `computeNextVestingScheduleIdForHolder` function could be made
public instead of external, allowing it to be called internally by the contract.
This would result in cheaper gas costs.

**Comment by GimerStackIt** [comment]
Fixed!
