### ISSUE TITLE
 Low readability of long literals in MAX_SUPPLY constant

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#18]
In the DefiSpotToken.sol file, the MAX_SUPPLY constant is defined as a
long literal 1000000000 ether. This long literal suffers from low readability,
making it difficult to quickly understand the value it represents.
To improve readability, it is suggested to split the long literals with the
underscore ('_') character. This would make the value easier to read and
understand at a glance.

**Comment by GimerStackIt** [comment]
Fixed!
