### ISSUE TITLE
Commented code parts, TODO comments and developer notes

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#19]
Several instances of commented code parts and TODO comments were
observed:
Within the TokenVesting contract, commented sections of code are
present within the whitelistClaim() function.
//require(IDefispotToken(address(_token)).mint(_amount), "mint failed!
");
Within the TokenVesting contract, developer notes are present within
the revoke() function.
require(vestingSchedule.revocable, "vesting is not revocable!"); // Do
we need this?
Within the TokenVesting contract, developer notes are present within
the release() function.
function release(
bytes32 vestingScheduleId,
uint256 amount // We shouldn't allow to release partially amounts.
)
Within the TokenVesting contract, developer notes are present within
the getVestingScheduleByAddressAndIndex() function.
// We don't need multiple vesting schedules for the same addres!!
function getVestingScheduleByAddressAndIndex(
Within the DefispotToken contract, TODO comment is present within
the mint() function.
function mint(uint256 amount) public onlyRole(MINTER) returns (bool) {
// @Todo Aggregar role rate adjuster.
_mint(msg.sender, amount);
return true;
}

**Comment by GimerStackIt** [comment]
Fixed!
