### ISSUE TITLE
Violation of Check-Eects-Interactions (CEI) paern in the _createVestingSchedule function

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#20]
State variables are updated after the external calls in
_createVestingSchedule() function.
As explained in [Solidity Security Considerations](https://docs.soliditylang.org/en/latest/security-considerations.html#security-considerations), it is best practice to follow
the [checks-effects-interactions](https://docs.soliditylang.org/en/latest/security-considerations.html#use-the-checks-effects-interactions-pattern) pattern when interacting with external
contracts to avoid reentrancy-related issues.
function _createVestingSchedule(... ) private returns (bool) {
//@audit external call
require(IDefispotToken(address(_token)).mint(_amount), "mint failed!")
;
//@audit external call
require(this.getWithdrawableAmount() >= _amount, "not enough funds!");
{ ... }
//@audit update of state variable
vestingSchedules[vestingScheduleId] = VestingSchedule( ... );
//@audit update of state variable
vestingSchedulesTotalAmount = vestingSchedulesTotalAmount + _amount;
//@audit update of state variable
vestingSchedulesIds.push(vestingScheduleId);
uint256 currentVestingCount = holdersVestingCount[_beneficiary];
//@audit update of state variable
holdersVestingCount[_beneficiary] = currentVestingCount + 1;
{ ... }
}

**Comment by GimerStackIt** [comment]
Reentrancy is not possible in this scenario with an ERC20 token. However, I adjusted it to follow the Check-Effect-Interact pattern. With this change, the validation: require(getWithdrawableAmount() >= _amount, "not enough funds!"); is not necessary. All tests passed.
