### ISSUE TITLE
Redundant the getCurrentTime wrapper leads to higher deployment cost

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#21]
The getCurrentTime() function appears to be redundant wrapper on
block.timestamp global variable. Such global variable is always accessible
and it does not require any additional getters. Current implementation leads
to extensive Gas usage during both deployment and usage.
```
function getCurrentTime() internal view virtual returns (uint256) {
return block.timestamp;
}
```

**Comment by GimerStackIt** [comment]
This function is crucial for testing purposes we are not going to remove it. The mock contract overrides this function to simulate how to advance time.
