### ISSUE TITLE
Redundant argument in the release function

### ISSUE THREAD

**Issue by thorcat** [DefiSpot/vesting-contract#22]
The release() function is designed to withdraw vested tokens from the TokenVesting contract to a given vesting beneficiary. This function requires the user to pass two arguments: vestingScheduleId and amount. The amount value must be lower or equal to the amount calculated at the given time, allowing for partial withdrawal. However, the amount variable is redundant, increasing complexity and requiring the user to provide additional arguments, leading to a lower user experience. Instead, the return value from _computeReleasableAmount() can be used to withdraw all possible
tokens after the given time.

**Comment by Gimer0x** [comment]
Remove the amount parameter.

**Comment by GimerStackIt** [comment]
Fixed!
